inherit_from: .rubocop_todo.yml

# General configuration
AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Gemfile.lock"
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Max: 100 # 100 lines blocks is probably too much...

require:
  - rubocop-rails
