inherit_from: .rubocop_todo.yml

# General configuration
AllCops:
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "Gemfile.lock"
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
