services:
  db:
    image: postgres:16.4
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:6.2
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgresql:
  storage:
