databases:
  - name: shorty
    databaseName: shorty_production
    user: shorty
    plan: free

services:
  - type: redis
    name: cache
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu

  - type: web
    name: shorty
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shorty
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CUNCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
