default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  port: 5432
  host: 127.0.0.1

development:
  <<: *default
  database: shorty_development

test:
  <<: *default
  database: shorty_test

production:
  <<: *default
  database: shorty_production
  username: shorty
  password: <%= ENV["SHORTY_DATABASE_PASSWORD"] %>
